export const FETCH_HOTELS = 'FETCH_HOTELS';
export const FETCH_HOTELS_SUCCESS = 'FETCH_HOTELS_SUCCESS';
export const FETCH_HOTELS_FAILED = 'FETCH_HOTELS_FAILED';

export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_FAILED = 'FETCH_COMMENT_FAILED';


