export const FETCH_HOTELS = 'FETCH_HOTELS';
export const FETCH_HOTELS_SUCCESS = 'FETCH_HOTELS_SUCCESS';
export const FETCH_HOTELS_FAILED = 'FETCH_HOTELS_FAILED';

export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_FAILED = 'FETCH_COMMENT_FAILED';

export const CREATE_HOTELS = 'CREATE_HOTELS';
export const CREATE_HOTELS_SUCCESS = 'CREATE_HOTELS_SUCCESS';
export const CREATE_HOTELS_FAILED = 'CREATE_HOTELS_FAILED';

export const CREATE_ANALYS = 'CREATE_ANALYS';
export const CREATE_ANALYS_SUCCESS = 'CREATE_ANALYS_SUCCESS';
export const CREATE_ANALYS_FAILED = 'CREATE_ANALYS_FAILED';

export const FETCH_HOTEL_DETAIL = 'FETCH_HOTEL_DETAIL';
export const FETCH_HOTEL_DETAIL_SUCCESS = 'FETCH_HOTEL_DETAIL_SUCCESS';
export const FETCH_HOTEL_DETAIL_FAILED = 'FETCH_HOTEL_DETAIL_FAILED';



