version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: front:1.0.1
    tmpfs:
      - /tmp
    command: nx serve admin
    ports:
      - '3001:3001'
    volumes:
      - .:/front:delegated
    tty: true
    stdin_open: true
